apiVersion: v1
kind: Namespace
metadata:
  name: trading
  labels:
    env: DEV
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adm-devtrade01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services"]
    verbs: ["get", "create", "delete"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-devtrade01
subjects:
  - kind: ServiceAccount
    name: adm-devtrade01
    namespace: trading
roleRef:
  kind: ClusterRole
  name: spark-cluster-role
  apiGroup: rbac.authorization.k8s.io